### ISSUE TITLE
Breaks cross-origin requests when logged in on SoundCloud.com

### ISSUE THREAD

**Issue by BinToss** [da2x/save-data#5] opened 2021-05-23 01:45 UTC
# Disabled
![image](https://user-images.githubusercontent.com/7243190/119245290-f77c3680-bb2c-11eb-9761-4d43c8de6ec4.png)
![Clipboard01 webp](https://user-images.githubusercontent.com/7243190/119245303-15499b80-bb2d-11eb-8557-c87376a1e8c6.png)
# Enabled
![image](https://user-images.githubusercontent.com/7243190/119245313-298d9880-bb2d-11eb-8f4b-3e9ceb613c44.png)
![image](https://user-images.githubusercontent.com/7243190/119245321-4629d080-bb2d-11eb-95e7-319616f3a2b6.png)

# Networking Errors
![image](https://user-images.githubusercontent.com/7243190/119245361-9d2fa580-bb2d-11eb-82fc-c1abb91be77d.png)
![image](https://user-images.githubusercontent.com/7243190/119245364-ad478500-bb2d-11eb-997a-88d9ac349104.png)
![image](https://user-images.githubusercontent.com/7243190/119245370-bc2e3780-bb2d-11eb-9bf5-bb940e817d83.png)

**Comment by BinToss** [comment] 2021-05-23 01:47
This seems to be due to a modification of the requests' Referrer Policy. Manually resent requests use the "unsafe-url" policy while blocked requests use the "origin" Referrer Policy.
![image](https://user-images.githubusercontent.com/7243190/119245411-0e6f5880-bb2e-11eb-904c-b575657b82d2.png)

**Comment by da2x** [comment] 2021-05-24 21:35
The extension doesn’t touch any of these headers.

Here’s all the header modifications it does: https://github.com/da2x/save-data/blob/d02ccfbfb1ff311c97b9a3d88f0d768bf1b6ee22/background.js#L27-L30

The server in question may modify what it sends back based on the presence of the header. (Which is kind of the point.) Does the problem reproduce with Chrome on Android set in data saver mode? It sends the same header as the extension.

**Comment by BinToss** [comment] 2021-06-08 09:45
So, I can't actually test that with the latest Chrome for Android. It seems Data Saver was replaced with the Lite mode setting which essentially uses a Google-hosted proxy server to compress data.

**Comment by da2x** [comment] 2021-06-08 13:10
Lite Mode also adds the `Save-Data: on` header.

**Comment by da2x** [comment] 2021-06-09 00:52
Does it also reproduce after disabling *all* other extensions and reloading the page?

**Comment by BinToss** [comment] 2021-06-16 09:07
Yup.

~~I discovered now that the initial GET requests don't have headers when I'm not logged in, but they do when I *am* logged in.~~
~~When logged in, GET requests' headers use the Origin referrer policy with an origin of https://soundcloud.com/ to request a resource from "a-v2.sndcdn.com".~~
[image](https://user-images.githubusercontent.com/7243190/122190632-d87c7600-ce46-11eb-94d1-5cde436460ae.png)

~~Right-clicking the failed GET request in the event log and selecting "Resend Request" changes the header to use the "unsafe-uri" referrer policy, which allows this CORS to succeed.~~

My findings were irrelevant.
This, however, seems more relevant:
![image](https://user-images.githubusercontent.com/7243190/122194988-cbfa1c80-ce4a-11eb-8137-7b4eeb82bdd6.png)

There's still very little information to go on by inspecting the request header...

**Comment by da2x** [comment] 2022-01-11 04:54
Duplicate of #6.

**Closed by da2x** 2022-01-11 04:54 UTC
